name: Publish release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  npm-publish:
    name: publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.22.8'

      - name: check if package.json version has been updated
        uses: EndBug/version-check@v1
        if: ${{ github.event_name != 'workflow_dispatch' }}
        id: check

      - name: build library
        if: steps.check.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          npm run install-all
          npm run lib
          touch .npmrc
          echo "//registry.npmjs.org/:_authToken=${NPM_ACCESS_TOKEN}" >> ./.npmrc

      - name: publish to npm
        if: steps.check.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        run: npm publish
